#puerto del servidor
server.port=8080

#configuracion del h2(base de datos en memoria)

spring.datasource.url=jdbc:h2:mem:cibertecdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#configuracion del jpa

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.formate.format_sql=true